http://data.doremus.org/vocabulary/function/composer composer
http://data.doremus.org/vocabulary/function/performer performer
http://data.doremus.org/vocabulary/function/chief_conductor chief conductor
http://data.doremus.org/vocabulary/function/sound_operator sound operator
http://data.doremus.org/vocabulary/function/librettist librettist
http://data.doremus.org/vocabulary/function/author author
http://data.doremus.org/vocabulary/function/audio_producer audio producer
http://data.doremus.org/vocabulary/function/publisher publisher
http://data.doremus.org/vocabulary/function/radio_producer radio producer
http://data.doremus.org/vocabulary/function/choral_director choral director
http://data.doremus.org/vocabulary/function/74 musicien metteur en ondes
http://data.doremus.org/vocabulary/function/actor actor
http://data.doremus.org/vocabulary/function/arranger arranger
http://data.doremus.org/vocabulary/function/sound_engineer sound engineer
http://data.doremus.org/vocabulary/function/narrator narrator
http://data.doremus.org/vocabulary/function/dancer dancer
http://data.doremus.org/vocabulary/function/lyricist lyricist
http://data.doremus.org/vocabulary/function/transcriber transcriber
http://data.doremus.org/vocabulary/function/musician_(performer) musician (performer)
http://data.doremus.org/vocabulary/function/sound_engineering_technician sound engineering technician
http://data.doremus.org/vocabulary/function/producer_(sound) None
http://data.doremus.org/vocabulary/function/orchestrator orchestrator
http://data.doremus.org/vocabulary/function/sponsor sponsor
http://data.doremus.org/vocabulary/function/creator_of_musical_reduction creator of musical reduction
http://data.doremus.org/vocabulary/function/mixing mixing
http://data.doremus.org/vocabulary/function/art_director art director
http://data.doremus.org/vocabulary/function/director director
http://data.doremus.org/vocabulary/function/translator translator
http://data.doremus.org/vocabulary/function/collector_of_field_material collector of field material
http://data.doremus.org/vocabulary/function/presenter presenter
http://data.doremus.org/vocabulary/function/video_producer video producer
http://data.doremus.org/vocabulary/function/creative_work None
http://data.doremus.org/vocabulary/function/creator_of_musical_revision creator of musical revision
http://data.doremus.org/vocabulary/function/author_of_argument author of argument
http://data.doremus.org/vocabulary/function/adapter adapter
http://data.doremus.org/vocabulary/function/performance None
http://data.doremus.org/vocabulary/function/musical_work None
http://data.doremus.org/vocabulary/function/publication None
http://data.doremus.org/vocabulary/function/casting None
http://data.doremus.org/vocabulary/function/remixer remixer
http://data.doremus.org/vocabulary/function/storyteller storyteller
http://data.doremus.org/vocabulary/function/creator_of_musical_reconstruction creator of musical reconstruction
http://data.doremus.org/vocabulary/function/performance_plan None
http://data.doremus.org/vocabulary/function/parodist parodist
http://data.doremus.org/vocabulary/function/recording None
http://data.doremus.org/vocabulary/function/sound-effects_engineer sound-effects engineer
http://data.doremus.org/vocabulary/function/disc_jockey disc jockey
http://data.doremus.org/vocabulary/function/creator_of_musical_harmonization creator of musical harmonization
http://data.doremus.org/vocabulary/function/editing None
http://data.doremus.org/vocabulary/function/drawer drawer
http://data.doremus.org/vocabulary/function/publishing_director publishing director
http://data.doremus.org/vocabulary/function/imitator imitator
http://data.doremus.org/vocabulary/function/film_director film director
http://data.doremus.org/vocabulary/function/20 chargé de réalisation
http://data.doremus.org/vocabulary/function/100 programmateur artistique
http://data.doremus.org/vocabulary/function/composer_of_cadenza composer of cadenza
http://data.doremus.org/vocabulary/function/programming_work None
http://data.doremus.org/vocabulary/function/author_of_afterword author of afterword
http://data.doremus.org/vocabulary/function/video_designer video designer
http://data.doremus.org/vocabulary/function/contributor contributor
http://data.doremus.org/vocabulary/function/composer_of_basso_continuo composer of basso continuo
http://data.doremus.org/vocabulary/function/editor_of_fingerings editor of fingerings
http://data.doremus.org/vocabulary/function/editor_of_the_bowing_marks editor of the bowing marks
http://data.doremus.org/vocabulary/function/compiler compiler
http://data.doremus.org/vocabulary/function/editor_of_pedal_markings editor of pedal markings
http://data.doremus.org/vocabulary/function/illustrator illustrator
http://data.doremus.org/vocabulary/function/author_of_preface author of preface
http://data.doremus.org/vocabulary/function/creator creator
http://data.doremus.org/vocabulary/function/auhor_of_annotations auhor of annotations
http://data.doremus.org/vocabulary/function/creator_of_musical_fantasy creator of musical fantasy
http://data.doremus.org/vocabulary/function/radio_director radio director
http://data.doremus.org/vocabulary/function/author_of_foreword author of foreword
http://data.doremus.org/vocabulary/function/author_of_introduction author of introduction
http://data.doremus.org/vocabulary/function/creator_of_musical_paraphrase creator of musical paraphrase
http://data.doremus.org/vocabulary/function/child_actor child actor
http://data.doremus.org/vocabulary/function/sound_technician sound technician
http://data.doremus.org/vocabulary/function/screenwriter screenwriter
http://data.doremus.org/vocabulary/function/musician_(creator) musician (creator)
http://data.doremus.org/vocabulary/function/dance_notator dance notator
http://data.doremus.org/vocabulary/function/live_electronic_conductor live electronic conductor
http://data.doremus.org/vocabulary/function/artistic_adviser artistic adviser
http://data.doremus.org/vocabulary/function/extra extra
http://data.doremus.org/vocabulary/function/sound_editor sound editor
http://data.doremus.org/vocabulary/function/choreographer choreographer
http://data.doremus.org/vocabulary/function/photographer photographer
http://data.doremus.org/vocabulary/function/manufacturer manufacturer
http://data.doremus.org/vocabulary/function/7 attaché de production (radio)
http://data.doremus.org/vocabulary/function/creator_of_musical_transposition creator of musical transposition
http://data.doremus.org/vocabulary/function/conductor conductor
http://data.doremus.org/vocabulary/function/24 chef de maîtrise
http://data.doremus.org/vocabulary/function/juggler juggler
http://data.doremus.org/vocabulary/function/set_designer set designer
http://data.doremus.org/vocabulary/function/mime mime
http://data.doremus.org/vocabulary/function/stage_director stage director
http://data.doremus.org/vocabulary/function/author_of_dialogue author of dialogue
http://data.doremus.org/vocabulary/function/literary_advisor literary advisor
http://data.doremus.org/vocabulary/function/painter painter
http://data.doremus.org/vocabulary/function/acrobat acrobat
http://data.doremus.org/vocabulary/function/producer_(show) producer (show)
http://data.doremus.org/vocabulary/function/printer printer
http://data.doremus.org/vocabulary/function/silent_actor silent actor
http://data.doremus.org/vocabulary/function/scenographer scenographer
http://data.doremus.org/vocabulary/function/lighting_designer lighting designer
http://data.doremus.org/vocabulary/function/editor editor
http://data.doremus.org/vocabulary/function/film_editor film editor
http://data.doremus.org/vocabulary/function/creator_of_musical_variation creator of musical variation
http://data.doremus.org/vocabulary/function/creator_of_musical_medley creator of musical medley
http://data.doremus.org/vocabulary/function/creator_of_musical_reminiscence creator of musical reminiscence
http://data.doremus.org/vocabulary/function/costume_designer costume designer
http://data.doremus.org/vocabulary/function/continuator continuator
http://data.doremus.org/vocabulary/function/programmer_(music_computing) programmer (music computing)
http://data.doremus.org/vocabulary/function/addressee addressee